Assigment 04 - Simon Chumacero Espada
SoftwareDevFundamentals/coding pull request #20
Opened 2024-01-09 19:05 UTC by stoic-programmer11

2024-01-10 13:23 UTC, marcos-x86 requested changes

2024-01-10 13:23 UTC, marcos-x86 commented on config/checkstyle/checkstyle.xml
> -    <!-- Checks for Headers                                -->
Why do you modified this configurations?

2024-01-10 13:23 UTC, marcos-x86 commented on src/main/java/bo/usfx/Example.java
> + * Este paquete contiene la clase Example,que
It's not necessary to add comments. But if you want to add them you have to change everything to English.

2024-01-10 13:23 UTC, marcos-x86 commented on src/main/java/bo/usfx/exampletdd/package-info.java
> +package bo.usfx.exampletdd;
It's not necessary to add this file, please remove it.

2024-01-10 13:23 UTC, marcos-x86 commented on src/main/java/bo/usfx/package-info.java
> +package bo.usfx;
It's not necessary to add this file, please remove it.

2024-01-10 13:23 UTC, marcos-x86 commented on src/main/java/simon/chumacero/espada/assigment2/Kata1.java
> +  private static final int SMELL_SERIE = 3;
The indentation level of this file is wrong, please reformat the code.

2024-01-10 13:23 UTC, marcos-x86 commented on src/main/java/simon/chumacero/espada/assigment3/Kata1.java
> +public final class Kata1 {
The indentation level of this file is wrong, please reformat the code.

2024-01-10 13:23 UTC, marcos-x86 commented on src/test/java/bo/usfx/exampletdd/WellTests.java
> +        Assert.assertEquals(Well.well(new String[]{"bad", "bad", "bad"}), "Fail!");
This change is already in the main branch, please update your branch everytime that you push new code.

2024-01-10 13:23 UTC, marcos-x86 commented on src/test/java/simon/chumacero/espada/test/assigment3/test/assigment4/Kata1Test.java
> +  public void testRowWeights() {
The indentation level of this file is wrong, please reformat the code.

2024-01-12 14:22 UTC, stoic-programmer11 commented
Thanks for the feedback

2024-01-12 14:22 UTC, closed without merging