Katas A03 - Walter Benjamin Vaquera Reyes
SoftwareDevFundamentals/coding pull request #4
Opened 2023-12-22 01:32 UTC by waltervaquera

Solutions of the Assigment 03 katas and their respective tests classes, appliying Checkstyles and the SonarLint plugin.

2023-12-22 01:35 UTC, waltervaquera commented
![image](https://github.com/SoftwareDevFundamentals/coding/assets/127642990/550221aa-5171-40c6-a8d9-9e16f43f3d8c)
![image](https://github.com/SoftwareDevFundamentals/coding/assets/127642990/c371ea4d-fca3-4e36-bf40-17aa94fb8c19)
![image](https://github.com/SoftwareDevFundamentals/coding/assets/127642990/ee038ecb-b3c1-4e98-a320-06af4494e518)
![image](https://github.com/SoftwareDevFundamentals/coding/assets/127642990/01a0be3d-dc32-40e8-9f75-0e76b3544819)
![image](https://github.com/SoftwareDevFundamentals/coding/assets/127642990/08f4ea90-6097-4098-a00f-e7ecdf7af900)

2024-01-10 14:08 UTC, marcos-x86 commented
|Overall Project|NaN% **`NaN%`**|:green_circle:|
|:-|:-|:-:|

> There is no coverage information present for the Files changed

2024-01-10 14:27 UTC, marcos-x86 requested changes

2024-01-10 14:27 UTC, marcos-x86 commented on build.gradle
> -jacocoTestReport {
Why do you delete this?

2024-01-10 14:27 UTC, marcos-x86 commented on src/test/java/bo/usfx/ExampleTests.java
> -package bo.usfx;
Don't delete this file, please restore it.

2024-01-10 14:27 UTC, marcos-x86 commented on src/main/java/bo/usfx/Example.java
> -package bo.usfx;
Don't delete this file, please restore it.

2024-01-10 14:27 UTC, marcos-x86 commented on coding
What is this file?

2024-01-10 14:33 UTC, closed without merging